services:
  mongodb:
    container_name: container-p5-mdb
    image: mongo:8
    healthcheck:
      start_period: 10s
      test: ["CMD", "mongosh", "--eval","db.runCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: 
      - p5_network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_p5_db:/data/db
      - mongo_p5_config:/data/configdb
  migration:
    build: .
    depends_on:
      mongodb:
        condition: service_healthy
    networks: 
    - p5_network
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_USER_READ: ${MONGO_USER_READ}
      MONGO_PASSWORD_READ: ${MONGO_PASSWORD_READ}
      MONGO_USER_READWRITE: ${MONGO_USER_READWRITE}
      MONGO_PASSWORD_READWRITE: ${MONGO_PASSWORD_READWRITE}
      MONGO_USER_ADMIN: ${MONGO_USER_ADMIN}
      MONGO_PASSWORD_ADMIN: ${MONGO_PASSWORD_ADMIN}
    volumes:
      - ./data:/app/data
      - ./src:/app/src
  migration-test:
    build: .
    depends_on: 
      migration:
        condition: service_completed_successfully
    networks: 
      - p5_network
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_USER_READ: ${MONGO_USER_READ}
      MONGO_PASSWORD_READ: ${MONGO_PASSWORD_READ}
      MONGO_USER_READWRITE: ${MONGO_USER_READWRITE}
      MONGO_PASSWORD_READWRITE: ${MONGO_PASSWORD_READWRITE}
      MONGO_USER_ADMIN: ${MONGO_USER_ADMIN}
      MONGO_PASSWORD_ADMIN: ${MONGO_PASSWORD_ADMIN}
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    command: python3 src/script_test_migration.py
volumes:
  mongo_p5_db:
    name: volume-p5-db
  mongo_p5_config:
    name: volume-p5-config
networks :
  p5_network:
    name: p5-migration-network